/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.posbd.energia.gui;

import br.ufmt.ic.posbd.energia.FabricaDAO;
import br.ufmt.ic.posbd.energia.dao.CidadeDAO;
import br.ufmt.ic.posbd.energia.dao.EnderecoDAO;
import br.ufmt.ic.posbd.energia.tableModel.EnderecoTableModel;
import br.ufmt.ic.posbd.energiapostgresql.entidade.Cidade;
import br.ufmt.ic.posbd.energiapostgresql.entidade.Endereco;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class EnderecoJPanel extends javax.swing.JPanel {

    private EnderecoTableModel tableModel;
    private EnderecoDAO dao = FabricaDAO.criarEnderecoDAO();

    /**
     * Creates new form Imovel
     */
    public EnderecoJPanel() {
        tableModel = new EnderecoTableModel(dao.listar());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idjLabel = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        localjLabel = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        editarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        cidadejButton1 = new javax.swing.JButton();
        nomecidadejTextField1 = new javax.swing.JTextField();
        localjLabel1 = new javax.swing.JLabel();
        ufjTextField = new javax.swing.JTextField();

        idjLabel.setText("Id:");

        idjTextField.setEditable(false);
        idjTextField.setEnabled(false);

        nomejLabel.setText("Endereço:");

        localjLabel.setText("Cidade:");

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Limpar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        cidadejButton1.setText("Buscar Cidade");
        cidadejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadejButton1ActionPerformed(evt);
            }
        });

        nomecidadejTextField1.setEditable(false);

        localjLabel1.setText("UF:");

        ufjTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(localjLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(excluirjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idjTextField)
                    .addComponent(nomejTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cidadejButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomecidadejTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(localjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ufjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localjLabel)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomecidadejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjLabel1)
                    .addComponent(cidadejButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirjButton)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        if (!nomejTextField.getText().equals("")) {
            Endereco endereco = new Endereco();

            endereco.setNome(nomejTextField.getText());
            
            int cidade_novo = Integer.parseInt(cidadejTextField.getText());
            endereco.setId_cidade(cidade_novo);

            if(!idjTextField.getText().equals("")){
                int id = Integer.parseInt(idjTextField.getText());
                endereco.setId(id);
                dao.alterar(endereco);
                JOptionPane.showMessageDialog(salvarjButton,
                    "Endereço atualizado com Sucesso!");
            }else{
                dao.inserir(endereco);
                JOptionPane.showMessageDialog(salvarjButton,
                    "Endereço inserido com Sucesso!");
            }

            tableModel.atualizar(dao.listar());

            cancelarjButtonActionPerformed(evt);

        }else{
            JOptionPane.showMessageDialog(nomejTextField,
                "Informe o campo nome!");
            nomejTextField.grabFocus();
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idjTextField.setText("");
        nomejTextField.setText("");
        cidadejTextField.setText("");
        nomecidadejTextField1.setText("");
        ufjTextField.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        cancelarjButtonActionPerformed(evt);
        if(tabelajTable.getSelectedRowCount() == 1){
            int linha = tabelajTable.getSelectedRow();
            Endereco edicao = tableModel.get(linha);
            nomejTextField.setText(edicao.getNome());
            cidadejTextField.setText(edicao.getId_cidade() + "");
            idjTextField.setText(edicao.getId() + "");
            cidadejButton1ActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(tabelajTable,
                "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();
        if(JOptionPane.showConfirmDialog(excluirjButton,
            "Deseja realmente excluir?")
        ==JOptionPane.YES_OPTION){

        for (int i = 0; i < linhas.length; i++) {
            Endereco endereco = tableModel.get(linhas[i]);
            dao.excluir(endereco.getId());
        }
        JOptionPane.showMessageDialog(tabelajTable,
            "Endereço removido com Sucesso!");
        tableModel.atualizar(dao.listar());
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void cidadejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadejButton1ActionPerformed
        // TODO add your handling code here:
        if(!cidadejTextField.getText().equals("")) {
            int id = Integer.parseInt(cidadejTextField.getText());

            try {
                Cidade cidade = new Cidade();
                cidade.setId(id);

                CidadeDAO dao2 = FabricaDAO.criarCidadeDAO();
                nomecidadejTextField1.setText(dao2.consultar(cidade.getId()).getNome());
                ufjTextField.setText(dao2.consultar(cidade.getId()).getUf());
            } catch (Exception e) {
                cidadejTextField.setText("");
                JOptionPane.showMessageDialog(cidadejButton1, "Cidade não encontrada!");
            }
        }else{
            JOptionPane.showMessageDialog(cidadejButton1, "Cidade não encontrada!");
        }
    }//GEN-LAST:event_cidadejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton cidadejButton1;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel localjLabel;
    private javax.swing.JLabel localjLabel1;
    private javax.swing.JTextField nomecidadejTextField1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    private javax.swing.JTextField ufjTextField;
    // End of variables declaration//GEN-END:variables
}
