/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.posbd.energia.gui;

import br.ufmt.ic.posbd.energia.FabricaDAO;
import br.ufmt.ic.posbd.energia.dao.AmbienteDAO;
import br.ufmt.ic.posbd.energia.dao.AparelhoDAO;
import br.ufmt.ic.posbd.energia.dao.CidadeDAO;
import br.ufmt.ic.posbd.energia.dao.EnderecoDAO;
import br.ufmt.ic.posbd.energia.dao.ImovelDAO;
import br.ufmt.ic.posbd.energia.dao.MovimentacaoDAO;
import br.ufmt.ic.posbd.energia.tableModel.MovimentacaoTableModel;
import br.ufmt.ic.posbd.energiamysql.entidade.Ambiente;
import br.ufmt.ic.posbd.energiamysql.entidade.Aparelho;
import br.ufmt.ic.posbd.energiamysql.entidade.Imovel;
import br.ufmt.ic.posbd.energiamysql.entidade.Movimentacao;
import br.ufmt.ic.posbd.energiapostgresql.entidade.Cidade;
import br.ufmt.ic.posbd.energiapostgresql.entidade.Endereco;
import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class LancamentoJPanel extends javax.swing.JPanel {

    private MovimentacaoTableModel tableModel;
    private MovimentacaoDAO dao = FabricaDAO.criarMovimentacaoDAO();

    /**
     * Creates new form Imovel
     */
    public LancamentoJPanel() {
        tableModel = new MovimentacaoTableModel(dao.listar());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idjLabel = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        nomejLabel = new javax.swing.JLabel();
        idimoveljTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        excluirjButton = new javax.swing.JButton();
        nomeimoveljTextField = new javax.swing.JTextField();
        nomejLabel1 = new javax.swing.JLabel();
        idambientejTextField = new javax.swing.JTextField();
        nomeambienteljTextField = new javax.swing.JTextField();
        ambientejButton = new javax.swing.JButton();
        imoveljButton2 = new javax.swing.JButton();
        localjLabel2 = new javax.swing.JLabel();
        nomecidadejTextField = new javax.swing.JTextField();
        localjLabel1 = new javax.swing.JLabel();
        ufjTextField = new javax.swing.JTextField();
        localjLabel = new javax.swing.JLabel();
        localjTextField = new javax.swing.JTextField();
        enderecojTextField = new javax.swing.JTextField();
        nomejLabel2 = new javax.swing.JLabel();
        mesjTextField = new javax.swing.JTextField();
        nomejLabel3 = new javax.swing.JLabel();
        nomejLabel4 = new javax.swing.JLabel();
        anojTextField = new javax.swing.JTextField();
        nomeambienteljTextField1 = new javax.swing.JTextField();
        nomeaparelhojTextField = new javax.swing.JTextField();
        localjLabel3 = new javax.swing.JLabel();
        potenciajTextField = new javax.swing.JTextField();
        localjLabel4 = new javax.swing.JLabel();
        nomejLabel5 = new javax.swing.JLabel();
        quantidadejTextField = new javax.swing.JTextField();
        nomejLabel6 = new javax.swing.JLabel();
        consumojTextField = new javax.swing.JTextField();
        nomejLabel7 = new javax.swing.JLabel();
        calcularjButton = new javax.swing.JButton();
        nomejLabel8 = new javax.swing.JLabel();
        custojTextField = new javax.swing.JTextField();
        aparelhojButton = new javax.swing.JButton();
        idaparelhojTextField1 = new javax.swing.JTextField();
        editarjButton = new javax.swing.JButton();

        idjLabel.setText("Id:");

        idjTextField.setEditable(false);
        idjTextField.setEnabled(false);

        nomejLabel.setText("Imóvel:");

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Limpar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        nomeimoveljTextField.setEditable(false);

        nomejLabel1.setText("Ambiente:");

        nomeambienteljTextField.setEditable(false);

        ambientejButton.setText("...");
        ambientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambientejButtonActionPerformed(evt);
            }
        });

        imoveljButton2.setText("...");
        imoveljButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imoveljButton2ActionPerformed(evt);
            }
        });

        localjLabel2.setText("Cidade:");

        nomecidadejTextField.setEditable(false);

        localjLabel1.setText("UF:");

        ufjTextField.setEditable(false);

        localjLabel.setText("Endereço:");

        localjTextField.setEditable(false);

        enderecojTextField.setEditable(false);
        enderecojTextField.setName(""); // NOI18N

        nomejLabel2.setText("Mês:");

        nomejLabel3.setText("Ano:");

        nomejLabel4.setText("Aparelho:");

        nomeambienteljTextField1.setEditable(false);

        nomeaparelhojTextField.setEditable(false);

        localjLabel3.setText("Potência:");

        potenciajTextField.setEditable(false);

        localjLabel4.setText("Watts");

        nomejLabel5.setText("Quantidade:");

        nomejLabel6.setText("Consumo:");

        nomejLabel7.setText("horas por mês");

        calcularjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        calcularjButton.setText("Calcular >>>");
        calcularjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularjButtonActionPerformed(evt);
            }
        });

        nomejLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomejLabel8.setText("Custo aproximado R$:");

        custojTextField.setEditable(false);
        custojTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        aparelhojButton.setText("...");
        aparelhojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparelhojButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomejLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(quantidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomejLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomejLabel7)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(localjLabel2)
                                                .addComponent(idjLabel)
                                                .addComponent(nomejLabel))
                                            .addGap(13, 13, 13))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomejLabel2)
                                            .addComponent(nomejLabel4)))
                                    .addComponent(salvarjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelarjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(excluirjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nomejLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(idaparelhojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(aparelhojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nomeaparelhojTextField)
                                                .addGap(18, 18, 18)
                                                .addComponent(localjLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(potenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(localjLabel4)
                                                .addGap(48, 48, 48))
                                            .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idimoveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imoveljButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeimoveljTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enderecojTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(calcularjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomejLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(custojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(idjTextField)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(nomejLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idambientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ambientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nomeambienteljTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(nomecidadejTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(localjLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ufjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(nomeambienteljTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(idimoveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeimoveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imoveljButton2)
                    .addComponent(localjLabel)
                    .addComponent(localjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjLabel1)
                    .addComponent(nomecidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel1)
                    .addComponent(nomeambienteljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambientejButton)
                    .addComponent(idambientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel2)
                    .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejLabel3)
                    .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel4)
                    .addComponent(nomeaparelhojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjLabel3)
                    .addComponent(potenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aparelhojButton)
                    .addComponent(idaparelhojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejLabel5)
                    .addComponent(consumojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejLabel6)
                    .addComponent(nomejLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejLabel8)
                    .addComponent(custojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarjButton)
                        .addGap(10, 10, 10)
                        .addComponent(editarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirjButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(nomeambienteljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        Movimentacao movimentacao = new Movimentacao();

        int idimovel_novo = Integer.parseInt(idimoveljTextField.getText());
        movimentacao.setImovel(idimovel_novo);

        int idambiente_novo = Integer.parseInt(idambientejTextField.getText());
        movimentacao.setAmbiente(idambiente_novo);

        int idaparelho_novo = Integer.parseInt(idaparelhojTextField1.getText());
        movimentacao.setAparelho(idaparelho_novo);

        int mes_novo = Integer.parseInt(mesjTextField.getText());
        movimentacao.setMes(mes_novo);
        
        int ano_novo = Integer.parseInt(anojTextField.getText());
        movimentacao.setAno(ano_novo);

        int quantidade_novo = Integer.parseInt(quantidadejTextField.getText());
        movimentacao.setQuantidade(quantidade_novo);
        
        int horas_mes_novo = Integer.parseInt(consumojTextField.getText());
        movimentacao.setHoras_mes(horas_mes_novo);
        
        float valor_novo = Float.parseFloat(custojTextField.getText());
        movimentacao.setValor(valor_novo);
        
        if(!idjTextField.getText().equals("")){
            int id = Integer.parseInt(idjTextField.getText());
            movimentacao.setId(id);
            dao.alterar(movimentacao);
            JOptionPane.showMessageDialog(salvarjButton,
                "Lançamento atualizado com sucesso!");
        }else{
            dao.inserir(movimentacao);
            JOptionPane.showMessageDialog(salvarjButton,
                "Lançamento inserido com sucesso!");
        }

        tableModel.atualizar(dao.listar());

        cancelarjButtonActionPerformed(evt);
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idjTextField.setText("");
        idimoveljTextField.setText("");
        nomeimoveljTextField.setText("");
        localjTextField.setText("");
        enderecojTextField.setText("");
        nomecidadejTextField.setText("");
        ufjTextField.setText("");
        idambientejTextField.setText("");
        nomeambienteljTextField.setText("");
        mesjTextField.setText("");
        anojTextField.setText("");
        idaparelhojTextField1.setText("");
        nomeaparelhojTextField.setText("");
        potenciajTextField.setText("");
        quantidadejTextField.setText("");
        consumojTextField.setText("");
        custojTextField.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();
        if(JOptionPane.showConfirmDialog(excluirjButton,
            "Deseja realmente excluir o lançamento?")
        ==JOptionPane.YES_OPTION){

        for (int i = 0; i < linhas.length; i++) {
            Movimentacao movimentacao = tableModel.get(linhas[i]);
            dao.excluir(movimentacao.getId());
        }
        JOptionPane.showMessageDialog(tabelajTable,
            "Lançamento removido com Sucesso!");
        tableModel.atualizar(dao.listar());
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void ambientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambientejButtonActionPerformed
        // TODO add your handling code here:
        if(!idambientejTextField.getText().equals("")) {
           int id_ambiente = Integer.parseInt(idambientejTextField.getText());
        
           Ambiente ambiente = new Ambiente();
           ambiente.setId(id_ambiente);
           AmbienteDAO daoAmbiente = FabricaDAO.criarAmbienteDAO();
           nomeambienteljTextField.setText(daoAmbiente.consultar(ambiente.getId()).getAmbiente());
        }else{
           JOptionPane.showMessageDialog(idimoveljTextField, "Ambiente não encontrado!");
        }
    }//GEN-LAST:event_ambientejButtonActionPerformed

    private void imoveljButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imoveljButton2ActionPerformed
        // TODO add your handling code here:
        if(!idimoveljTextField.getText().equals("")) {
           int id_imovel = Integer.parseInt(idimoveljTextField.getText());

           try {
               Imovel imovel = new Imovel();
               imovel.setId(id_imovel);
               ImovelDAO daoImovel = FabricaDAO.criarImovelDAO();
               nomeimoveljTextField.setText(daoImovel.consultar(imovel.getId()).getNomeImovel());
               int local_novo = daoImovel.consultar(imovel.getId()).getLocalidade();
               localjTextField.setText(local_novo + "");
               
               int id_endereco = Integer.parseInt(localjTextField.getText());
               Endereco endereco = new Endereco();
               endereco.setId(id_endereco);
               EnderecoDAO daoEndereco = FabricaDAO.criarEnderecoDAO();
               enderecojTextField.setText(daoEndereco.consultar(endereco.getId()).getNome());
               int cidade_novo = daoEndereco.consultar(endereco.getId()).getId_cidade();

               Cidade cidade = new Cidade();
               cidade.setId(cidade_novo);
               CidadeDAO daoCidade = FabricaDAO.criarCidadeDAO();
               nomecidadejTextField.setText(daoCidade.consultar(cidade.getId()).getNome());
               ufjTextField.setText(daoCidade.consultar(cidade.getId()).getUf());
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(idimoveljTextField, "Imóvel não encontrado!");
            }
        }else{
           JOptionPane.showMessageDialog(idimoveljTextField, "Imóvel não encontrado!");
        }
        
    }//GEN-LAST:event_imoveljButton2ActionPerformed

    private void calcularjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularjButtonActionPerformed
        // TODO add your handling code here:
        int potencia = Integer.parseInt(potenciajTextField.getText());
        int consumo = Integer.parseInt(consumojTextField.getText());
        int quantidade = Integer.parseInt(quantidadejTextField.getText());
        
        int R = (((potencia * consumo) * quantidade) / 1000);
        double tarifa = 0.50765;
        Double valor = (tarifa * R);
        
        String valorstr = new DecimalFormat("0.00").format(valor);
        valorstr = valorstr.replace(",",".");
        custojTextField.setText(valorstr+"");
    }//GEN-LAST:event_calcularjButtonActionPerformed

    private void aparelhojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparelhojButtonActionPerformed
        // TODO add your handling code here:
        if(!idaparelhojTextField1.getText().equals("")) {
           int id_aparelho = Integer.parseInt(idaparelhojTextField1.getText());
        
           Aparelho aparelho = new Aparelho();
           aparelho.setId(id_aparelho);
           AparelhoDAO daoAparelho = FabricaDAO.criarAparelhoDAO();
           nomeaparelhojTextField.setText(daoAparelho.consultar(aparelho.getId()).getAparelho());
           potenciajTextField.setText(daoAparelho.consultar(aparelho.getId()).getPotencia() + "");
        }else{
           JOptionPane.showMessageDialog(idimoveljTextField, "Ambiente não encontrado!");
        }
    }//GEN-LAST:event_aparelhojButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        cancelarjButtonActionPerformed(evt);
        if(tabelajTable.getSelectedRowCount() == 1){
            int linha = tabelajTable.getSelectedRow();
            Movimentacao edicao = tableModel.get(linha);

            idimoveljTextField.setText(edicao.getImovel()+"");
            imoveljButton2ActionPerformed(evt);
            idambientejTextField.setText(edicao.getAmbiente()+"");
            ambientejButtonActionPerformed(evt);
            mesjTextField.setText(edicao.getMes()+"");
            anojTextField.setText(edicao.getAno()+"");
            idaparelhojTextField1.setText(edicao.getAparelho()+"");
            aparelhojButtonActionPerformed(evt);
            quantidadejTextField.setText(edicao.getQuantidade()+"");
            consumojTextField.setText(edicao.getHoras_mes()+"");
            custojTextField.setText(edicao.getValor()+"");
            idjTextField.setText(edicao.getId() + "");
        }else{
            JOptionPane.showMessageDialog(tabelajTable,
                "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambientejButton;
    private javax.swing.JTextField anojTextField;
    private javax.swing.JButton aparelhojButton;
    private javax.swing.JButton calcularjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JTextField consumojTextField;
    private javax.swing.JTextField custojTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTextField idambientejTextField;
    private javax.swing.JTextField idaparelhojTextField1;
    private javax.swing.JTextField idimoveljTextField;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JButton imoveljButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel localjLabel;
    private javax.swing.JLabel localjLabel1;
    private javax.swing.JLabel localjLabel2;
    private javax.swing.JLabel localjLabel3;
    private javax.swing.JLabel localjLabel4;
    private javax.swing.JTextField localjTextField;
    private javax.swing.JTextField mesjTextField;
    private javax.swing.JTextField nomeambienteljTextField;
    private javax.swing.JTextField nomeambienteljTextField1;
    private javax.swing.JTextField nomeaparelhojTextField;
    private javax.swing.JTextField nomecidadejTextField;
    private javax.swing.JTextField nomeimoveljTextField;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JLabel nomejLabel1;
    private javax.swing.JLabel nomejLabel2;
    private javax.swing.JLabel nomejLabel3;
    private javax.swing.JLabel nomejLabel4;
    private javax.swing.JLabel nomejLabel5;
    private javax.swing.JLabel nomejLabel6;
    private javax.swing.JLabel nomejLabel7;
    private javax.swing.JLabel nomejLabel8;
    private javax.swing.JTextField potenciajTextField;
    private javax.swing.JTextField quantidadejTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    private javax.swing.JTextField ufjTextField;
    // End of variables declaration//GEN-END:variables

}
