/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.ufmt.ic.posbd.energia.gui;

import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    private void setConteudo(JPanel tela){
        conteudojPanel.removeAll();
        conteudojPanel.add(tela);
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudojPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imoveljMenuItem = new javax.swing.JMenuItem();
        ambientejMenuItem = new javax.swing.JMenuItem();
        aparelhojMenuItem = new javax.swing.JMenuItem();
        enderecojMenuItem = new javax.swing.JMenuItem();
        cidadejMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        movimentacaojMenuItem = new javax.swing.JMenuItem();
        sairjMenu3 = new javax.swing.JMenu();
        sairjMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consumo de Energia Elétrica");
        setExtendedState(6);

        conteudojPanel.setLayout(new javax.swing.BoxLayout(conteudojPanel, javax.swing.BoxLayout.LINE_AXIS));

        jMenu1.setText("Cadastros");

        imoveljMenuItem.setText("Imóvel");
        imoveljMenuItem.setActionCommand("Imovel");
        imoveljMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imoveljMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(imoveljMenuItem);

        ambientejMenuItem.setText("Ambiente");
        ambientejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambientejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ambientejMenuItem);

        aparelhojMenuItem.setText("Aparelho");
        aparelhojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparelhojMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(aparelhojMenuItem);

        enderecojMenuItem.setText("Endereço");
        enderecojMenuItem.setActionCommand("Endereco");
        enderecojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecojMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(enderecojMenuItem);

        cidadejMenuItem.setText("Cidade");
        cidadejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cidadejMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lançamentos");
        jMenu2.setActionCommand("lancamentos");

        movimentacaojMenuItem.setText("Lançamento");
        movimentacaojMenuItem.setActionCommand("Lancamento");
        movimentacaojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimentacaojMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(movimentacaojMenuItem);

        jMenuBar1.add(jMenu2);

        sairjMenu3.setText("Sair");

        sairjMenuItem1.setText("Sair");
        sairjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjMenuItem1ActionPerformed(evt);
            }
        });
        sairjMenu3.add(sairjMenuItem1);

        jMenuBar1.add(sairjMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudojPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imoveljMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imoveljMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new ImovelJPanel());
    }//GEN-LAST:event_imoveljMenuItemActionPerformed

    private void ambientejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambientejMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new AmbienteJPanel());
    }//GEN-LAST:event_ambientejMenuItemActionPerformed

    private void aparelhojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparelhojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new AparelhoJPanel());
    }//GEN-LAST:event_aparelhojMenuItemActionPerformed

    private void enderecojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new EnderecoJPanel());
    }//GEN-LAST:event_enderecojMenuItemActionPerformed

    private void cidadejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadejMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new CidadeJPanel());
    }//GEN-LAST:event_cidadejMenuItemActionPerformed

    private void movimentacaojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimentacaojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new LancamentoJPanel());
    }//GEN-LAST:event_movimentacaojMenuItemActionPerformed

    private void sairjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairjMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ambientejMenuItem;
    private javax.swing.JMenuItem aparelhojMenuItem;
    private javax.swing.JMenuItem cidadejMenuItem;
    private javax.swing.JPanel conteudojPanel;
    private javax.swing.JMenuItem enderecojMenuItem;
    private javax.swing.JMenuItem imoveljMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem movimentacaojMenuItem;
    private javax.swing.JMenu sairjMenu3;
    private javax.swing.JMenuItem sairjMenuItem1;
    // End of variables declaration//GEN-END:variables
}
